Feature: Added all DBT models for Singapore Development
KV-APAC-DNA/gitdbtadbplt001 pull request #33
Opened 2024-01-29 06:21 UTC by apahil01

### Feature: Added all DBT models for Regional SAP Sellin job

## Description & motivation
Create all models with SDL tables as source and created next set of models in this job. This request contains all the model builds from last sprint(Sprint 4)
Created separate folder structure for MDS subject area
Create Seperate folder for each Country in Onesea

## To-do before merge
- [ ] Make sure source tables are present in PROD.

## Models built
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/apahil01/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/apahil01/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Sr No. | EDW Models
-- | --
1 | sgpedw_integration__edw_sg_pos_analysis
2 | sgpedw_integration__edw_vw_sg_pos_analysis
3 | sgpedw_integration__edw_sg_sellin_analysis
4 | sgpedw_integration__edw_vw_sg_sellin_analysis
5 | sgpedw_integration__edw_vw_sg_sellin_sales_fact
6 | sgpedw_integration__edw_vw_sg_time_dim
7 | sgpedw_integration__edw_vw_sg_curr_dim
8 | sgpedw_integration__edw_vw_sg_listprice
9 | sgpedw_integration__edw_vw_sg_pos_sales_fact
10 | sgpedw_integration__edw_vw_sg_material_dim
11 | sgpedw_integration__edw_vw_sg_customer_dim

Sr No. | ITG Models
-- | --
1 | sgpitg_integration__itg_sg_scan_data_dfi
2 | sgpitg_integration__itg_sg_scan_data_guardian
3 | sgpitg_integration__itg_sg_scan_data_marketplace
4 | sgpitg_integration__itg_sg_scan_data_scommerce
5 | sgpitg_integration__itg_sg_scan_data_redmart
6 | sgpitg_integration__itg_sg_scan_data_ntuc
7 | sgpitg_integration__itg_sg_scan_data_amazon
8 | sgpitg_integration__itg_sg_pos_sales_fact
9 | sgpitg_integration__itg_mds_sg_product_mapping
10 | sgpitg_integration__itg_mds_sg_store_master
11 | sgpitg_integration__sdl_raw_sg_scan_data_watsons
12 | sgpitg_integration__sdl_raw_sg_scan_data_dfi
13 | sgpitg_integration__sdl_raw_sg_scan_data_guardian
14 | sgpitg_integration__sdl_raw_sg_scan_data_marketplace
15 | sgpitg_integration__sdl_raw_sg_scan_data_scommerce
16 | sgpitg_integration__sdl_raw_sg_scan_data_redmart
17 | sgpitg_integration__sdl_raw_sg_scan_data_ntuc
18 | sgpitg_integration__sdl_raw_sg_scan_data_amazon
19 | sgpitg_integration__itg_mds_sg_customer_hierarchy
20 | sgpitg_integration__itg_mds_sg_product_hierarchy
21 | sgpitg_integration__itg_mds_sg_ps_weights
22 | sgpitg_integration__itg_mds_sg_ps_targets
23 | sgpitg_integration__itg_sg_tp_closed_month
24 | sgpitg_integration__sdl_raw_sg_tp_closed_month
25 | sgpitg_integration__sdl_raw_sg_tp_closed_year_bal
26 | sgpitg_integration__sdl_raw_sg_zuellig_sellout
27 | sgpitg_integration__itg_sg_tp_closed_year_bal
28 | sgpitg_integration__itg_sg_zuellig_sellout
29 | sgpitg_integration__itg_sg_zuellig_customer_mapping
30 | sgpitg_integration__itg_sg_zuellig_product_mapping
31 | sgpitg_integration__itg_sg_ciw_mapping
 
Sr No. | WKS Models
-- | --
1 | sgpwks_integration__wks_sg_listprice

</body>

</html>

## Validation of models:
We validated all ITG and EDW models for Structural and Data validation(wherever possible). Data validation will be done in corresponding sprints, once CDL-SDL data is validated successfully.

## Checklist:

- [x] I confirmed and have no doubts that there are no confidential data, sensitive details and credentials in my code.
- [x] My pull request represents one logical piece of work.
- [x] My commits are related to the pull request and look clean.
- [x] My SQL follows the [dbt Labs style guide](https://docs.getdbt.com/guides/best-practices/how-we-style/0-how-we-style-our-dbt-projects).
- [x] I have materialized my models appropriately.
- [x] I have added appropriate tests and documentation to any new models.
- [ ] I have updated the README file.
- [x] I have validated the SQL in any late-binding views.

2024-01-31 13:31 UTC, awahi01 approved these changes

2024-02-06 06:59 UTC, kkr01ken approved these changes
The table structure is validated and it looks good

2024-02-06 08:10 UTC, Murali-MK commented on models/singapore/sgpedw_integration/common/view/sgpedw_integration__edw_vw_os_time_dim.sql
this one need not be in singapore or other market models.. i think its  created in regional. lets use that in other references

2024-02-06 08:14 UTC, Murali-MK commented on models/singapore/sgpedw_integration/common/view/sgpedw_integration__edw_vw_sg_material_dim.sql
can we put the filters sls org or ean - i mean the base filters in the first source reference itself..

2024-02-06 08:18 UTC, Murali-MK commented on models/singapore/sgpedw_integration/currency/master/view/sgpedw_integration__edw_vw_sg_curr_dim.sql
can we see if this can be created in regional - for all markets

2024-02-06 08:28 UTC, Murali-MK commented on models/singapore/sgpwks_integration/customer360/sgpwks_integration__wks_singapore_regional_sellout_offtake_npd.sql
In general, Customer and Product hierarchy column selections can be created as a model in regional and referenced in C360 scripts.  This would reduce the similar model getting built across each market

2024-02-06 08:28 UTC, Murali-MK requested changes
Have updated comments.

2024-02-09 08:06 UTC, apahil01 commented on models/singapore/sgpedw_integration/common/view/sgpedw_integration__edw_vw_os_time_dim.sql
Will be taking this up in Sprint 6.

2024-02-09 08:06 UTC, apahil01 commented on models/singapore/sgpedw_integration/common/view/sgpedw_integration__edw_vw_sg_material_dim.sql
Will be taking this up in Sprint 6.

2024-02-09 08:06 UTC, apahil01 commented on models/singapore/sgpwks_integration/customer360/sgpwks_integration__wks_singapore_regional_sellout_offtake_npd.sql
Will be taking this up in Sprint 6.

2024-02-09 08:47 UTC, Murali-MK approved these changes
Comments would be implemented in the next release

2024-02-09 08:49 UTC, Murali-MK commented on models/singapore/sgpedw_integration/currency/master/view/sgpedw_integration__edw_vw_sg_curr_dim.sql
Would be implemented later

2024-02-09 09:41 UTC, jc3-jeeva approved these changes

2024-02-09 12:53 UTC, awahi01 approved these changes

2024-02-09 13:07 UTC, vkaram01 approved these changes
Structural validation is completed.

2024-02-09 13:35 UTC, merged